services:
  web:
    build: .
    container_name: portfolio_cyber
    restart: unless-stopped
    volumes:
      - .:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 128M
